- import_tasks: precheck.yml
  tags:
    - always

- name: Ensure that modify_dir_path is defined
  assert:
    that:
      - modify_dir_path is defined
      - modify_dir_path | length > 0

- name: Set default modified_append_tag
  set_fact:
    modified_append_tag: "{{ lookup('pipe','date +-modified-%Y%m%d%H%M%S') }}"
  when: modified_append_tag is undefined

- name: Copy Dockerfile to Dockerfile.modified
  copy:
    src: "{{ modify_dir_path }}/Dockerfile"
    dest: "{{ modify_dir_path }}/Dockerfile.modified"

- name: Replace FROM directive
  lineinfile:
    path: "{{ modify_dir_path }}/Dockerfile.modified"
    regexp: "^FROM "
    line: "FROM {{ source_image }}"

- name: Add LABEL modified_append_tag={{ modified_append_tag }}
  lineinfile:
    path: "{{ modify_dir_path }}/Dockerfile.modified"
    insertafter: "^FROM "
    line: "LABEL modified_append_tag={{ modified_append_tag }}"

- name: Modify image from {{ modify_dir_path }}
  command: "{{ build_commands[container_build_tool] }} --tag {{ target_image | default(source_image) }}{{ modified_append_tag }} --file Dockerfile.modified --network host ./"
  #FIXME: buildah should not required root commands to build an image
  become: "{{ true if build_commands[container_build_tool] == 'buildah' else false }}"
  args:
    chdir: "{{ modify_dir_path }}"
