- name: Set default facts
  include_role:
    name: tripleo-modify-image
    tasks_from: set_defaults.yml

- name: Copy Dockerfile to Dockerfile.modified
  copy:
    src: "{{ modify_dir_path }}/Dockerfile"
    dest: "{{ modify_dir_path }}/Dockerfile.modified"

- name: Replace FROM directive
  lineinfile:
    path: "{{ modify_dir_path }}/Dockerfile.modified"
    regexp: "^FROM "
    line: "FROM {{ source_image }}"

- name: Add LABEL modified_append_tag={{ modified_append_tag }}
  lineinfile:
    path: "{{ modify_dir_path }}/Dockerfile.modified"
    insertafter: "^FROM "
    line: "LABEL modified_append_tag={{ modified_append_tag }}"

- name: Modify image  
  docker_image:
    name: "{{ modified_image }}{{ modified_append_tag }}"
    path: "{{ modify_dir_path }}"
    dockerfile: Dockerfile.modified

