- name: Ensure that source_image is defined
  assert:
    that:
      - source_image is defined
      - source_image | length > 0

- name: Ensure that container_build_tool is correctly set
  fail: msg="{{ container_build_tool }} is not a valid value for container_build_tool. Pick docker or buildah."
  when: container_build_tool not in ['docker', 'buildah']
