FROM {{ source_image }}
LABEL modified_append_tag={{ modified_append_tag }}

USER root

COPY refspec_projects /root/refspec_projects
RUN /bin/bash -c 'rpm -qi python-pip || yum install -y python-pip; cd /; for X in $(ls /root/refspec_projects/*.tar.gz); do pip install $X; done; rm -Rf /root/refspec_projects'

USER "{{ original_user }}"
